const express = require('express');
const router = express.Router();

const claimSummaryRouter = require('./claim_summary_endpoint');
const claimExplanationRouter = require('./claim_explanation_endpoint');
const claimIngestRouter = require('./claim_ingest_endpoint');
const reviewQueueRouter = require('./review_queue_endpoint');
const claimSearchRouter = require('./claim_search_endpoint');
const claimStatsRouter = require('./claim_stats_endpoint');
const claimsIntelligenceRouter = require('./claims_intelligence_endpoint');
const matchLearningRouter = require('./match_learning_endpoint');
const matchFeedbackRouter = require('./match_feedback_endpoint');
const batchNormalizeRouter = require('./batch_normalize_endpoint');
const listEndpointRouter = require('./list_endpoint');
const detailEndpointRouter = require('./detail_endpoint');
const customerCasesRouter = require('./customer_cases_endpoint');
const billingEndpointRouter = require('./billing_endpoint');
const providerApprovalEndpointRouter = require('./provider_approval_endpoint');
const agreementsEndpointRouter = require('../legal/agreements_endpoint');
const uploadsEndpointRouter = require('./uploads_endpoint');
const providerConnectionsEndpointRouter = require('./provider_connections_endpoint');
const fileAccessEndpointRouter = require('./file_access_endpoint');
const operationsEndpointRouter = require('./operations_endpoint');
const intakeUploadRouter = require('../intake/intake_upload_endpoint');
const { requireOperatorRole } = require('./role_middleware');

router.use(customerCasesRouter);
router.use(billingEndpointRouter);
router.use(providerApprovalEndpointRouter);
router.use(agreementsEndpointRouter);
router.use(intakeUploadRouter);

router.use(requireOperatorRole);
router.use(claimSummaryRouter);
router.use(claimExplanationRouter);
router.use(claimIngestRouter);
router.use(reviewQueueRouter);
router.use(claimSearchRouter);
router.use(claimStatsRouter);
router.use(claimsIntelligenceRouter);
router.use(matchLearningRouter);
router.use(matchFeedbackRouter);
router.use(batchNormalizeRouter);
router.use(listEndpointRouter);
router.use(detailEndpointRouter);
router.use(uploadsEndpointRouter);
router.use(providerConnectionsEndpointRouter);
router.use(fileAccessEndpointRouter);
router.use(operationsEndpointRouter);

module.exports = router;
